## Script to calculate the effect of low and medium gain on integration area
## the ratio will be used to correct z values in the EEMs

## Script created April 2018 by KBG

## Data was generated by running 5 integration areas per day each on med. and low gain
## for 3 days May 14-16, 2018


calculate.gain.ratio <- function(){
#### LIBRARIES ################################################################
library(tidyverse)
###############################################################################

#### FILEPATHS ################################################################
dir_input <- file.path("/Users", "kbg", "Documents", "UC_Berkeley", "EEA_DOC", "Aqualog_EEMs", "PARAFAC_KBG")
###############################################################################

#### READ IN SAMPLE LIST AND CREATE DATA FRAME OF UNIQUE INTEGRATION AREAS
gain.data <- read_tsv(file.path(dir_input, "aqualog_gain_data.txt"))


#### REGRESSION OF MEDIUM VS. LOW GAIN ON INTEGRATION AREA
# plot(integration_area ~ factor(gain), data= gain.data)
gain.fit <- lm(integration_area ~ gain, gain.data)
#summary(gain.fit)


#### CALCULATE THE RATIO OF MED/LOW GAIN ON INTEGRATION AREA
gain.med.low.ratio <- as.numeric((gain.fit$coefficients[1] + gain.fit$coefficients[2])/gain.fit$coefficients[1])

return(gain.med.low.ratio)
}

### OLD REGRESSION USING

#int.area.df <- read_tsv(file.path(dir_input, "eem_sample_info.txt")) %>%
#  select(yr_mo, int_area, int_gain) %>%
#  unique()

#plot(int_area ~ factor(int_gain), data= int.area.df)
#gain.fit2 <- lm(int.area.df$int_area ~ int_gain, data= int.area.df)
#summary(gain.fit)
#plot(gain.fit)
#gain.med.low.ratio2 <- as.numeric((gain.fit2$coefficients[1] + gain.fit2$coefficients[2])/gain.fit2$coefficients[1])
