---
title: "raw data to rasters"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(raster)
```

### Import data

```{r message=FALSE, warning=FALSE}

raw <- list.files("../EEms_Raw", recursive = TRUE)

raw <- raw[str_detect(raw, "data_export/.*Processed Contour")]

data <- list()

for (i in 1:length(raw)) {
  data[[i]] <- read_tsv(paste0("../EEms_Raw/", raw[i]), skip = 3, col_names = FALSE)
  colnames(data[[i]]) <- c("ex", "em", "z")
  names(data)[i] <- str_replace_all(raw[i], "\\/", "X")
}

```

### trim data

```{r}

trim <- lapply(data, function(x) filter(x, 
                                        em>.95*ex+50, 
                                        em<2*ex-30,
                                        ex>245))

```

### sample names

```{r}

names <- str_replace_all(raw, "\\/", "X") %>%
  str_extract(pattern = ".*\\-") %>%
  str_sub(end = -3)

```

### Generate rasters

```{r}

plots <- list()

for (i in 1:length(trim)) {
  plots[[i]] <- ggplot(trim[[i]], aes(x = ex, y = em, z = z, fill = z, color = z)) +
  geom_tile() +
  scale_fill_continuous(type = "viridis") +
  scale_colour_continuous(type = "viridis") +
  geom_contour(color = "yellow", alpha = .3) +
  ggtitle(names[i]) +
  coord_fixed()
}

```

### Export images

NOTE: I intentionally deleted the eems/ folder after combining the pdfs. If you want to save these somewhere, designate the folder in the path below.

```{r}

for (i in 1:length(plots)) {
  ggsave(paste0("eems/",names[i], ".pdf"), plots[[i]], width = 8, height = 9)
}

```




